# Generated by Django 4.2.7 on 2023-12-24 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="risk",
            name="created_datetime",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="risk",
            name="updated_datetime",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="risk",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_mitigated", "NOT MITIGATED"),
                    ("partially_mitigated", "PARTIALLY MITIGATED"),
                    ("fully_mitigated", "FULLY MITIGATED"),
                ],
                max_length=32,
            ),
        ),
    ]
